apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: url-shortener
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
- deployment.yaml
- service.yaml
- pvc.yaml
- ingress.yaml
- servicemonitor.yaml

commonLabels:
  app.kubernetes.io/name: url-shortener
  app.kubernetes.io/part-of: single-node-gitops
  app.kubernetes.io/version: "1.0.0"

commonAnnotations:
  config.kubernetes.io/origin: |
    configuredIn: k8s/kustomization.yaml
    configuredBy:
      apiVersion: kustomize.config.k8s.io/v1beta1
      kind: Kustomization

images:
- name: your-registry:30500/url-shortener
  newTag: "latest"
