apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: url-shortener-data
  namespace: url-shortener
  labels:
    app: url-shortener
    app.kubernetes.io/name: url-shortener
    app.kubernetes.io/part-of: single-node-gitops
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path # K3s default storage class
  resources:
    requests:
      storage: 1Gi
